repos:
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ffb6a759a979008c0e6dff86e39f4745a2d9eac4
    hooks:
      - id: prettier
        files: \.(md|yml|yaml)
        args: [--prose-wrap=preserve]
